#!/usr/bin/php
<?php
error_reporting(0);

require_once __DIR__ . "/registrar/autoload.php";

\logger::$filename = __DIR__ . "/../var/pmopenprovider.log";
\logger::$loglevel = \logger::LEVEL_DEBUG & ~logger::LEVEL_ISP_RESULT;

Config::$REGNAME = "openprovider";
Config::$NOTICE_USER = "registrar";

Module::run( $argv );
